"use client";

import React, { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, Clock3, Plus, Route, Settings2, Target, X } from "lucide-react";
import type { TaskTemplate } from "@/lib/taskTemplates";
import { TASK_TEMPLATE_REFRESH_EVENT, TASK_TEMPLATE_REFRESH_STORAGE_KEY } from "@/lib/taskTemplates";
import { isTourTemplate, TOUR_TEMPLATE_CATEGORY } from "@/lib/tourTemplates";
import { navigateWithinSpa } from "@/lib/spaNavigation";
import {
  invalidateWorkspaceResource,
  notifyWorkspaceResourcesChanged,
  preloadWorkspaceRoute,
  taskDataKey,
  tasksDataKey,
  writeCachedResource,
} from "@/lib/workspaceData";

type TourForm = {
  name: string;
  color: string;
};

const blankForm: TourForm = {
  name: "",
  color: "#BFDBFE",
};

function isHexColor(value: string) {
  return /^#[0-9a-fA-F]{6}$/.test(value);
}

function sortTourTemplates(templates: TaskTemplate[]) {
  return [...templates].filter(isTourTemplate).sort((a, b) => a.name.localeCompare(b.name));
}

export default function ToursClient({ initialTemplates }: { initialTemplates: TaskTemplate[] }) {
  const [templates, setTemplates] = useState<TaskTemplate[]>(initialTemplates);
  const [modalOpen, setModalOpen] = useState(false);
  const [form, setForm] = useState<TourForm>(blankForm);
  const [createError, setCreateError] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const router = useRouter();

  useEffect(() => {
    setTemplates(initialTemplates);
  }, [initialTemplates]);

  const tours = useMemo(() => sortTourTemplates(templates), [templates]);

  const summary = useMemo(() => {
    const autogenerated = tours.filter((tour) => (tour.regularDays || []).length > 0 || (tour.regularTimes || []).length > 0 || Object.keys(tour.regularTimesByDay || {}).length > 0).length;
    const importTargets = tours.filter((tour) => tour.schoolTourImportTarget).length;
    return { autogenerated, importTargets };
  }, [tours]);

  function openCreate() {
    setForm(blankForm);
    setCreateError("");
    setModalOpen(true);
  }

  function closeModal() {
    if (isCreating) return;
    setModalOpen(false);
    setCreateError("");
  }

  async function createTour(event?: React.FormEvent<HTMLFormElement>) {
    event?.preventDefault();
    const trimmedName = form.name.trim();
    if (!trimmedName) return;
    try {
      setIsCreating(true);
      setCreateError("");
      const res = await fetch("/api/task-templates", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: trimmedName,
          category: TOUR_TEMPLATE_CATEGORY,
          color: form.color.trim() || "#BFDBFE",
          description: "Tour type for roster planning.",
        }),
      });
      if (!res.ok) throw new Error("Failed to add tour type");
      const created = (await res.json()) as TaskTemplate;
      const nextTemplates = [...templates, created];
      setTemplates(nextTemplates);
      writeCachedResource(tasksDataKey(), nextTemplates);
      writeCachedResource(taskDataKey(created.id), created);
      notifyWorkspaceResourcesChanged([tasksDataKey(), taskDataKey(created.id)]);
      invalidateWorkspaceResource("editor");
      window.dispatchEvent(new Event(TASK_TEMPLATE_REFRESH_EVENT));
      try {
        window.localStorage.setItem(TASK_TEMPLATE_REFRESH_STORAGE_KEY, new Date().toISOString());
      } catch (error) {
        console.error(error);
      }
      const href = `/tours/${created.id}`;
      if (!navigateWithinSpa(href)) router.push(href);
      setModalOpen(false);
    } catch (err) {
      console.error(err);
      setCreateError("Failed to add tour type.");
    } finally {
      setIsCreating(false);
    }
  }

  function openTour(tour: TaskTemplate) {
    const href = `/tours/${tour.id}`;
    if (!navigateWithinSpa(href)) router.push(href);
  }

  return (
    <div className="workspace-page">
      <div className="flex w-full flex-col items-start space-y-7">
        <div className="flex w-full flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <h1 className="page-title">Tours</h1>
            <p className="page-description mt-1.5">Manage reusable tour types for roster planning and autofill.</p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <button className="btn btn-primary px-4" onClick={openCreate}>
              <Plus className="h-4 w-4 text-white" strokeWidth={2.3} aria-hidden="true" />
              <span className="text-[14px] font-medium">Add tour type</span>
            </button>
          </div>
        </div>

        <div className="grid w-full gap-3 sm:grid-cols-3">
          <div className="surface-panel px-4 py-3">
            <div className="flex items-center gap-3">
              <span className="grid h-10 w-10 place-items-center rounded-[8px] bg-[var(--accent-soft)] text-[var(--accent)]">
                <Route className="h-5 w-5" aria-hidden="true" />
              </span>
              <div>
                <p className="text-[12px] font-bold uppercase text-[var(--muted)]">Types</p>
                <p className="text-[20px] font-bold text-[var(--ink)]">{tours.length}</p>
              </div>
            </div>
          </div>
          <div className="surface-panel px-4 py-3">
            <div className="flex items-center gap-3">
              <span className="grid h-10 w-10 place-items-center rounded-[8px] bg-[var(--accent-soft)] text-[var(--accent)]">
                <Clock3 className="h-5 w-5" aria-hidden="true" />
              </span>
              <div>
                <p className="text-[12px] font-bold uppercase text-[var(--muted)]">Autofill Rules</p>
                <p className="text-[20px] font-bold text-[var(--ink)]">{summary.autogenerated}</p>
              </div>
            </div>
          </div>
          <div className="surface-panel px-4 py-3">
            <div className="flex items-center gap-3">
              <span className="grid h-10 w-10 place-items-center rounded-[8px] bg-[var(--accent-soft)] text-[var(--accent)]">
                <Target className="h-5 w-5" aria-hidden="true" />
              </span>
              <div>
                <p className="text-[12px] font-bold uppercase text-[var(--muted)]">Import Target</p>
                <p className="text-[20px] font-bold text-[var(--ink)]">{summary.importTargets}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="surface-panel">
          <div className="overflow-x-auto">
            <table className="data-table min-w-[880px] table-fixed">
              <colgroup>
                <col />
                <col className="w-[19%]" />
                <col className="w-[19%]" />
                <col className="w-[120px]" />
              </colgroup>
              <thead className="text-[15px] text-slate-900">
                <tr className="border-b border-[var(--border)]">
                  <th className="px-4 py-4 text-left font-bold tracking-[0.01em]">
                    <span className="inline-flex items-center gap-2">
                      Tour type
                      <ChevronDown className="h-3.5 w-3.5" aria-hidden="true" />
                    </span>
                  </th>
                  <th className="px-4 py-4 text-left font-bold tracking-[0.01em]">Schedule</th>
                  <th className="px-4 py-4 text-left font-bold tracking-[0.01em]">Role</th>
                  <th className="px-4 py-4 text-right font-bold tracking-[0.01em]">Actions</th>
                </tr>
              </thead>
              <tbody className="[&_tr:last-child]:border-b-0">
                {tours.map((tour) => {
                  const href = `/tours/${tour.id}`;
                  const scheduleCount =
                    (tour.regularDays || []).length +
                    (tour.regularTimes || []).length +
                    Object.values(tour.regularTimesByDay || {}).reduce((count, times) => count + (Array.isArray(times) ? times.length : 0), 0);
                  return (
                    <tr
                      key={tour.id}
                      className="cursor-pointer border-b border-[var(--border)] hover:bg-[var(--surface-subtle)]"
                      onMouseEnter={() => {
                        preloadWorkspaceRoute(href);
                        router.prefetch(href);
                      }}
                      onClick={() => openTour(tour)}
                    >
                      <td className="align-middle px-4 py-4">
                        <span className="flex min-w-0 items-center gap-4 text-[15px] font-bold text-[var(--ink)]">
                          <span className="relative grid h-10 w-10 shrink-0 place-items-center rounded-[8px] bg-[var(--surface-subtle)] text-[var(--accent)]">
                            <Route className="h-5 w-5" aria-hidden="true" />
                            <span
                              className="absolute -right-1 -top-1 h-4 w-4 rounded-full border border-white"
                              style={{ backgroundColor: tour.color || "#fff" }}
                              aria-hidden="true"
                              title={tour.color || "default"}
                            />
                          </span>
                          <span className="truncate">{tour.name}</span>
                        </span>
                      </td>
                      <td className="align-middle px-4 py-4 text-[15px] font-bold text-[var(--ink)]">
                        {scheduleCount > 0 ? `${scheduleCount} rule${scheduleCount === 1 ? "" : "s"}` : "Manual"}
                      </td>
                      <td className="align-middle px-4 py-4 text-[15px] font-semibold text-[var(--muted-strong)]">
                        {tour.schoolTourImportTarget ? "Import target" : tour.mustManned ? "Must be manned" : "Standard"}
                      </td>
                      <td className="align-middle px-4 py-4">
                        <div className="flex justify-end gap-2">
                          <button className="icon-button h-9 w-10" onClick={(event) => { event.stopPropagation(); openTour(tour); }} aria-label={`Edit ${tour.name}`} title="Edit tour type">
                            <Settings2 className="h-4 w-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
                {tours.length === 0 && (
                  <tr>
                    <td colSpan={4} className="py-10 text-center text-[15px] text-[var(--muted)]">
                      No tour types yet. Add one to make it available in roster planning.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
          <div className="table-footer">
            {tours.length} tour type{tours.length === 1 ? "" : "s"}
          </div>
        </div>

        {modalOpen && (
          <div className="fixed inset-0 z-[2147483647] flex items-center justify-center bg-black/40 px-4" onClick={closeModal}>
            <form
              className="w-full max-w-xl overflow-hidden rounded-[8px] border border-[var(--border)] bg-white shadow-xl"
              onClick={(event) => event.stopPropagation()}
              onSubmit={createTour}
            >
              <div className="flex items-center justify-between px-6 py-4">
                <div>
                  <h2 className="text-xl font-semibold">Add tour type</h2>
                  <p className="text-sm text-slate-600">Create a reusable tour type for rosters.</p>
                </div>
                <button
                  type="button"
                  className="rounded-[10px] p-2 text-slate-500 transition hover:bg-[var(--surface-subtle)] hover:text-slate-700"
                  onClick={closeModal}
                  aria-label="Close"
                  disabled={isCreating}
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              <div className="space-y-5 px-6 pb-5 text-[14px]" style={{ color: "#1A1B25" }}>
                <div>
                  <label className="mb-1 block text-sm font-semibold" htmlFor="tour-name" style={{ color: "#1A1B25" }}>
                    Name
                  </label>
                  <input
                    id="tour-name"
                    className="input w-full text-[14px]"
                    value={form.name}
                    onChange={(event) => setForm((prev) => ({ ...prev, name: event.target.value }))}
                    autoFocus
                    required
                  />
                </div>

                <div>
                  <label className="mb-1 block text-sm font-semibold" htmlFor="tour-color" style={{ color: "#1A1B25" }}>
                    Colour
                  </label>
                  <div className="flex items-center gap-3">
                    <input
                      type="color"
                      value={isHexColor(form.color) ? form.color : "#BFDBFE"}
                      onChange={(event) => setForm((prev) => ({ ...prev, color: event.target.value }))}
                      aria-label="Pick tour colour"
                      className="h-10 w-12 cursor-pointer rounded-md border border-[var(--border)] bg-white p-1"
                    />
                    <input
                      id="tour-color"
                      className="input min-w-0 flex-1 text-[14px]"
                      value={form.color}
                      onChange={(event) => setForm((prev) => ({ ...prev, color: event.target.value }))}
                      placeholder="#BFDBFE"
                    />
                    <span
                      className="h-8 w-8 shrink-0 rounded-full border border-slate-300"
                      style={{ backgroundColor: form.color || "#fff" }}
                      aria-hidden="true"
                    />
                  </div>
                </div>

                {createError && <p className="text-sm text-red-600">{createError}</p>}
              </div>

              <div className="flex items-center justify-end gap-3 bg-white px-6 py-4">
                <button
                  type="button"
                  className="btn h-[30px] justify-center text-black/80 hover:text-black"
                  style={{ width: "65px", boxShadow: "inset 0 0 0 1px #CFCFCF", borderRadius: "6px", border: "none", background: "white" }}
                  onClick={closeModal}
                  disabled={isCreating}
                >
                  Cancel
                </button>
                <button
                  className="btn btn-primary h-[30px] px-4"
                  style={{ borderRadius: "6px" }}
                  type="submit"
                  disabled={isCreating || !form.name.trim()}
                >
                  {isCreating ? "Creating..." : "Create"}
                </button>
              </div>
            </form>
          </div>
        )}
      </div>
    </div>
  );
}
